spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1213abc..
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
      #druid参考官方配置
    initial-size: 1
    max-active: 20
    max-idle: 30
    min-idle: 5
    max-wait: 60000

  freemarker:
    request-context-attribute: ctx
#    cache: true
server:
  port: 80
  context-path: /hospital
  tomcat:
      max-http-header-size: 8192



wechat:
# 公众平台id
  mpAppId: a3a1faf6fee8fb21868a89cdfe326fec
# 公众平台密钥
  mpAppSecret: 11b9109f356573077836d29b044730fc
# 公众平台token
  token: jingbao
# 商户号
  mchId: 1399772202
# 商户密钥
  mchKey: Ljfybj6622676Ljfybj6622676Ljfybj
# 支付地址
  wxPayUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
# 查询地址
  wxQueryUrl: https://api.mch.weixin.qq.com/pay/orderquery
# 商户证书路径
  keyPath:
# 微信支付异步通知地址
  notifyUrl:
# 微信模版id
  templateId:
    orderStatus:

his:
 apiUrl: http://218.14.221.14:8099/wechat.asmx

redis:
 host: 127.0.0.1
 prot: 6379
 auth: